services:
  rdgen:
    # use bryangerlach/rdgen:latest for the latest build
    image: bryangerlach/rdgen:latest
    restart: unless-stopped
    environment:
      SECRET_KEY: "django-insecure-!(t-!f#6g#sr%yfded9(xha)g+=!6craeez^cp+*&bz_7vdk61"
      GHUSER: "umiddalimov1"
      GHBEARER: "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"
      GENURL: "https://3kto.ru/dcl"
      PROTOCOL: "https"
      REPONAME: "rdgen"
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
